config/routes.rb
RailsEcommProject::Application.routes.draw do
  # Devise user authentication
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # CKEditor
  mount Ckeditor::Engine => '/ckeditor'


# add routes for orders
    resources :orders, only: [:index, :show] do
     member do
     patch :mark_as_paid
    end
  end

  namespace :admin do
    resources :customers, only: [:index]
  end

  # Root route
  root 'home#index' # Defines the homepage
  post 'place_order', to: 'home#place_order', as: 'place_order'

  # Home and product-related routes
  get 'home/index'
  get 'products/search', to: 'products#search', as: 'product_search'
  patch 'update_cart/:id', to: 'home#update_cart', as: 'update_cart'
  resources :orders, only: [:index]
  get 'thank_you', to: 'home#thank_you', as: 'thank_you'
  delete 'remove_product/:id', to: 'home#remove_product', as: 'remove_product'
  delete 'empty', to: 'home#empty_cart', as: 'empty_cart'

  # Route to product detail page
  get 'home/:id', to: 'home#show', as: :store_product

  # Checkout routes
  # Renaming resources :checkout to avoid conflict with custom routes
  resources :checkouts, only: [:new, :create, :show], as: :order_checkout
  get 'checkout/success', to: 'home#checkout_success', as: 'checkout_success'
  get 'checkout/cancel', to: 'home#checkout_cancel', as: 'checkout_cancel'
  post 'checkout', to: 'home#checkout', as: 'process_checkout'
  post 'checkout', to: 'home#checkout', as: :checkout

  # PayPal route
  post 'paypal_checkout', to: 'home#paypal_checkout', as: 'paypal_checkout'

  # Static pages
  get 'page/:id', to: 'home#page', as: 'page'
  get 'search/:id', to: 'search#category', as: 'category'

  # Sales and new products
  get 'sale', to: 'home#sale', as: 'sale'
  get 'new', to: 'home#new', as: 'new'

  # Search routes
  get 'search', to: 'home#search', as: 'search'
  get 'search_results', to: 'home#search_results', as: 'search_results'
  post 'search_results', to: 'home#search_results'

  # Shopping cart routes
  get 'cart', to: 'home#cart', as: 'cart'
  #get 'empty', to: 'home#empty_cart', as: 'empty_cart'
  get 'add_product/:id', to: 'home#add_product', as: 'add_product'
 # get 'remove_product/:id', to: 'home#remove_product', as: 'remove_product'

  # Additional checkout routes
  post 'create', to: 'home#create', as: 'create'
  get 'edit_cart', to: 'home#edit_cart', as: 'edit_cart'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenShop</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Flash Messages Section -->
  <% flash.each do |type, message| %>
    <div class="alert <%= "alert-#{type == 'notice' ? 'info' : 'danger'}" %>">
      <%= message %>
    </div>
  <% end %>

  <header>
    <% categories = Category.all %>
    <% pages = Page.all %>
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">GreenShop!</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'On Sale!', sale_path %></li>
            <% pages.each do |page| %>
              <li><%= link_to page.title, page_path(id: page.id) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Cart', cart_path %></li>
            <% if user_signed_in? %>
              <% if current_user.email == "admin@example.com" %>
                <li><%= link_to 'Admin Dashboard', admin_dashboard_path %></li>
              <% end %>
              <li><%= link_to 'My Orders', orders_path %></li>
              <li><%= link_to 'My Account', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %></li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </div> <!-- /.navbar -->
  </header>

  <div class="col-xs-6 col-sm-3 sidebar-offcanvas categories" id="sidebar" role="navigation">
    <div class="list-group">
      <a href="#" class="list-group-item active">Categories</a>
      <%= link_to 'On Sale!', sale_path, class: "list-group-item" %>
      <%= link_to 'New!', new_path, class: "list-group-item" %>
      <% categories.each do |category| %>
        <%= link_to category.title, category_path(id: category.id), class: "list-group-item" %>
      <% end %>
    </div>
  </div><!--/span-->

  <div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-xs-12 col-sm-9">
        <p class="pull-right visible-xs">
          <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>

        <%= render 'search/search' %>

        <div class="message-output">
          <%= render 'message/message' %>
        </div>
        
        <section>
          <%= yield %>
        </section>
      </div><!--/span-->
    </div><!--/row-->

    <hr>

    <footer>
      <p>&copy; GreenShop 2024</p>
    </footer>
  </div><!--/.container-->
</body>
</html>